// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARv1I2wdzA0DY3_jTN_E8SBgP5430vPYE',
    appId: '1:422893936257:web:8e42b54783e8d9739a7780',
    messagingSenderId: '422893936257',
    projectId: 'dispense-cabinet',
    authDomain: 'dispense-cabinet.firebaseapp.com',
    storageBucket: 'dispense-cabinet.firebasestorage.app',
    measurementId: 'G-1T8S5EC21E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITJIyra-jTV6QTLXnS2ji3sulobeRLuk',
    appId: '1:422893936257:android:79e12a2566ab52b79a7780',
    messagingSenderId: '422893936257',
    projectId: 'dispense-cabinet',
    storageBucket: 'dispense-cabinet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2Z7KtRzcrWyj8kA8kjT4Ebr5LwK2G0A',
    appId: '1:422893936257:ios:4a5cc7707a969c7f9a7780',
    messagingSenderId: '422893936257',
    projectId: 'dispense-cabinet',
    storageBucket: 'dispense-cabinet.firebasestorage.app',
    iosClientId: '422893936257-ascm8lk1ckjre5gqqvbtv673ch0m8ndp.apps.googleusercontent.com',
    iosBundleId: 'cab.vend.user',
  );
}
